### ISSUE TITLE
Using AssImp to load models that have multiple textures and objects

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#112]
<a href="https://github.com/alexanderbock"><img src="https://avatars.githubusercontent.com/u/4921724?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [alexanderbock](https://github.com/alexanderbock)**
_Friday Jul 08, 2016 at 09:06 GMT_
_Originally opened as https://github.com/OpenSpace/OpenSpace-Development/issues/114_

---

For example Rosetta:
https://www.dropbox.com/s/1dozz14wnsth59s/rosetta.zip

**Comment by kbladin** [comment]
Suggestion:

- Models are still loaded one at a time as separate scene graph nodes since some parts of the model might require spice data for positioning and rotations.
- Using .obj with .mtl as a standard so that textures don't have to be specified explicitly in the scenegraph node mod. the mtl can just be exported from the modeling program and other texture types / material properties can be specified.

**Comment by chuan9** [comment]
@alexanderbock I open your model using assimp, but the texture size is zero. I haven't met an obj with multi texture and I have the same question. If the model has multi-texture, how to render its color in fragment shader?

**Comment by alexanderbock** [comment]
>5 years 😢
