### ISSUE TITLE
Stars visible during the day

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1148]
Goto the surface of earth. Look up, there are stars but should not be.

**Comment by GPayne** [comment]
This is too hard.

**Comment by hedbergj** [comment]
I'm never sure how much these comments get read, but this issue seems so important and so ignored over the last few years and I'm not sure why. It's maybe the most glaring and obvious physical inconsistency in the whole application.

I'm sure someone could add an `if h < 70km & lat/long in dayside = true -> star opacity = map(h,70,0,1,0)` or something to fake it until the atmosphere physics correctly obscures them during the day time. 

It derails presentations (Q: Why are there stars in the daytime? A: I don't know), confuses kids (and migrating birds), and might suggest the atmospheres are not doing something they should be physics-wise. 

It would be so cool to be able to simulate a sunset (which the atmo does do very well) but also see the stars appearing one by one, depending on their brightness, kinda like real life.

Tag = [Elephant in the Room]

**Comment by alexanderbock** [comment]
@hedbergj   We had a meeting recently to make sure that it becomes more obvious that we **are** and have been reading these comments.  In fact, this is kind of feedback is probably one of the best feedback channels.

I have actually been the one that has been pushing this ticket down on the priority list as I was under the impression that it wasn't a *big deal* but I see the error of my ways now, so thank you

**Comment by hedbergj** [comment]
Thanks @alexanderbock  - I have noticed an uptick in communication, which is great. Going forward, I'll just affectionately and  respectfully call you @Aristotlebock :) 

https://cerncourier.com/a/looking-at-the-stars-from-a-well/

**Comment by hedbergj** [comment]
Just putting this here: https://www.osapublishing.org/josa/fulltext.cfm?uri=josa-49-6-626&id=51829 (but, there's probably more recent work on the topic)

**Comment by ylvaselling** [comment]
Fixed in PR #2188
