### ISSUE TITLE
SessionRecording not respecting anchor/aim correctly 

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1161]
When playing back a recording that includes anchor and aim, the playback seems to only use the anchor, not the aim.

**Comment by micahnyc** [comment]
Closing as playback now behaves as expected

**Comment by GPayne** [comment]
With typical usage it seems as if the issue were resolved, but session recording does not actually handle anchor & aim. Since it saves the camera positions, playback with anchor & aim will work only if the simulation time is force-changed to when it was recorded. This is the typical way that playback is used ("Force time change to recorded time" is by default checked in the GUI).

A practical example where this fails is the "ISS view of the earth below": start a recording with anchor=earth & aim=ISS with the camera looking straight down at the ground below while following the ISS path. It would be useful to be able to play it back to show the ISS overflight at any selected date / time. However, the view will be wrong unless the time is set exactly to when it was recorded.

Implementing this support will require OrbitalNavigator::interpolateRetargetAim to be called at every playback frame when in anchor & aim mode.

**Comment by GPayne** [comment]
I polled some power users about their uses of session recording and the time-independent modes of playback (when simulation time is not force-changed to when it was recorded). None of them use session recording in this way, or have plans to.

This makes it tempting to close this issue since as described above, anchor & aim does technically work when simulation time is force-changed at playback. However, I think that the ISS use-case described above is still a legitimate case where a user might want to recreate the anchor & aim playback at a different time (in this case the position of the ISS at their current time).

I'm going to look into using existing `openspace.navigation` & `openspace.pathNavigation` commands to see if it's possible for a user to do this type of thing in a script rather than a session recording.
