### ISSUE TITLE
Screenshot path setting for SessionRecording

### ISSUE THREAD

**Issue by hedbergj** [OpenSpace/OpenSpace#1172]
Possible Enhancement: When using enableTakeScreenShotDuringPlayback( ), it would be helpful to have the option to be able to set the directory each time, rather than only using the  SCREENSHOTS = "${BASE}/screenshots" setting. Perhaps as a second argument after the framerate? Currently, if multiple sessionrecordings are saved as screenshots, they all go into the same timestamped folder and it can be hard to separate them later. 
eg: 

enableTakeScreenShotDuringPlayback(60, screenshots/scene1 )
enableTakeScreenShotDuringPlayback(60, screenshots/scene2 )

or something like that.

**Comment by alexanderbock** [comment]
It's unfortunately not that easy to pass it as a parameter as we don't have a way of handling a stack of screenshot folders.  With this solution, I think users would expect that the screenshots/scene1 folder would only be used during the session playback and then gets reset to the previous value.
Since the session playback is actually using the same functionality as the F12 screenshot button, that is not easy to achieve.

I implemented a feature that might work just as well for you;  there is a new Lua function `openspace.setScreenshotFolder` that does what you suggest without the need of a stack; so your solution would become:

```lua
openspace.setScreenshotFolder(openspace.absPath("${BASE}/screenshots/scene1"));
openspace.sessionRecording.enableTakeScreenShotDuringPlayback(60);
-- .. play back scene 1

openspace.setScreenshotFolder(openspace.absPath("${BASE}/screenshots/scene2"));
-- .. play back scene 2

openspace.setScreenshotFolder(openspace.absPath("${BASE}/screenshots"));  -- if necessary
```

I'll leave it up to @hedbergj  to close the ticket if this solution suffices

**Comment by hedbergj** [comment]
Awesome - that sounds like a fine solution. (I'll wait until I see #1385 close then give it a whirl)

**Comment by hedbergj** [comment]
...like a charm. Thank you.
