### ISSUE TITLE
Error while loading the asteroids scene

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#1202]
This error comes up when loading the “Asteroids” scene:
```
SmallSolarSystemBody (Error)    Unable to convert field 7 to double value (invalid_argument exception) at line 1164/3469 of C:\Users\<<>>\Downloads\OpenSpace-0.15.2-RC\OpenSpace-0.15.2-RC\sync\http\sssb_data_transneptunian_object_asteroid\1/sssb_data_transneptunian_object_asteroid.csv
```

**Comment by GPayne** [comment]
Closing this with commit **df22eeb**. Errors like this in a single data line are now logged with _info_ instead, since only the problem line is ignored and the rest of the data is still used in the scene.
Fixing the data file itself is not the best option, because the file in question came straight from JPL SBDB, and occasionally there are errors.
