### ISSUE TITLE
Loading some temporal layers does not work anymore

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#1204]
Report from Alex @ NCMNS

•	Activation of sea surface temperature color layer on Earth causes no change.

**Comment by micahnyc** [comment]
As per: https://worldview.earthdata.nasa.gov/?l=GHRSST_L4_G1SST_Sea_Surface_Temperature,Reference_Labels(hidden),Reference_Features(hidden),Coastlines,VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor


"Temporal coverage: 21 June 2010 - 08 December 2019

29 January 2020 Notice: The GHRSST Sea Surface Temperature (L4, G1SST) has been producing poor quality SST results since 9 December 2019. The imagery has been removed from 9 December 2019 to present. We advise users to consider using the GHRSST Sea Surface Temperature (L4, MUR) layer, which provides comparable data at the same spatial sampling and coverage as G1SST." 

so we should consider changing the layer we include to the MUR (or not include this layer).
