### ISSUE TITLE
Add an extension for recordings

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#1211]
When recording a session, the file that is generated doesn't have any file extension.  Maybe we want to add one (and potentially a different one depending on whether it's a text format or binary format)

**Comment by micahnyc** [comment]
i have been using .osrecording ....we could do something like spice where we put a b for binary. .osrecordingb? .osbrecording?

I like the idea of prefixing a extension with '**os**' because it denotes that this is a filetype that openspace made up, and not something that is going to be compatible with anything else. (When I was making the UI tests, I was using a .ostest as a file format.)

**Comment by alexanderbock** [comment]
How about `.osrec` to keep it a bit shorter?  And `.osbrec` for the binary?  Or vice versa..  `.osrec` for binary and `.ostrec` for textual?

I do enjoy the `os` prefix as well

**Comment by GPayne** [comment]
I like `.osrec` for for the normal binary format, and `.osrectxt` for the less-commonly-used ascii text version.

**Comment by alexanderbock** [comment]
Closed in  36bff67
