### ISSUE TITLE
Improving the visual quality of the RenderableTrails

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#125]
1. Rendering lines as billboarded quads and applying a transfer function to make them look visually more impressive
2. Having the option of fading out the color with progressing time (http://www.space.com/33676-rosetta-probe-s-complicated-orbit-of-comet-67p-visualized-2-year-time-lapse.html)

**Comment by kbladin** [comment]
There is a new class `RenderableTrailNew` that is able to replace both `RenderableTrail` and `RenderablePath` so that we hopefully can have just one `RenderableTrail` when we are done. The new class can render time stamps, fade and draw the last segment in high precision so that it does not wiggle around if you go in close to an object orbiting the sun for example. It also does not do any recalculations using SPICE when updating (except for one call to get the latest position of the "body"). Also you only specify a time range for the path and delta time samples (no EarthOrbitRatio mumbo jumbo that does not make any sense for space crafts to determine the sample delta time). This class might not be perfect yet but it can in its current state replace both of the old ones so we we have the new visual improvements it maybe can be implemented in the new one directly or we can make a manual merge of the two when we are done.

**Comment by kbladin** [comment]
Also, suggestion:
Using a geometry shader to generate quads and sample a one-dimensional function (distance to the center of the line basically) to get the color and/or alpha value for each fragment.

**Comment by alexanderbock** [comment]
This might be fulfilled enough with https://github.com/OpenSpace/OpenSpace/pull/1026 ?

**Comment by jccosta** [comment]
Yes. I am closing this issue in favor of #1026.
