### ISSUE TITLE
Option to orbit at constant latitude

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1372]
When Orbiting Earth for example, it would be nice if you could rotate at a constant latitude so that you could show specific bands of the planet. 

Currently this is possible if the pilot adds the correct amount of constant roll as the rotation is being applied but an option could be added to the orbitalnavigator to do this for them.

**Comment by WeirdRubberDuck** [comment]
This was added with PR #1667, as an "IdleBehavior" of the orbital navigator. The `OrbitAtConstantLatitude` option orbits around the "North vector" of a node, while keeping the camera's local rotation. If the up-vector points upwards on the screen, the camera will rotate to the right

The implementation is really simple and needs some testing. For example, maybe it's always desired to rotate to the right, even if a planet's up vector is pointing downwards on the screen?

**Comment by alexanderbock** [comment]
@WeirdRubberDuck  isn't this fixed with the camera paths?

**Comment by WeirdRubberDuck** [comment]
@alexanderbock the behavior Micah was looking for was something different. Rather than an automatic orbit, he wanted the ability to lock part of the rotation during manual rotation, so that we can for example only move the camera over a certain latitude band 

Do I remember that correctly, @micahnyc ?

**Comment by alexanderbock** [comment]
Micah says "Yes"
