### ISSUE TITLE
Camera starts off-center from the focus node at startup sometimes

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#1376]

**Comment by GPayne** [comment]
This seems to happen more often in the missions such as NewHorizons or Rosetta

**Comment by alexanderbock** [comment]
I think it might be related to how long the startup takes, as I feel that this offset is bigger when running in Debug mode.  My current theory:
// loading loading loading
set the camera to point at the object where it is *now*
// loading loading loading
update the position of the object to the new *now* but forgetting to update the camera with it

**Comment by GPayne** [comment]
I suspect it is related to length of startup time also. I have tested different profiles and observed that at startup, the simulation time starts ticking the moment you leave the launcher window and continues while waiting for the init screen to disappear. A camera shift due to this would be much less noticeable if focused on a probe vs. a planet.
