### ISSUE TITLE
Setting UpperLimit in profile or asset is ignored

### ISSUE THREAD

**Issue by Roxeena** [OpenSpace/OpenSpace#1409]
When setting the UpperLimit of rendered asteroids in the profile it gets ignored. It might be because the value gets overwritten when the file is read at a later stage. It works to set the UpperLimit in a javascript file instead.

**Comment by WeirdRubberDuck** [comment]
The case seems to be the same for setting the `UpperLimit` in the asset dictionary. 

Whatever value is set for the upper limit is overwritten in the `enderableSmallBody::initializeFileReading()` function: https://github.com/OpenSpace/OpenSpace/blob/f7cd107744183958c3b906839f5b3bb11376c172/modules/space/rendering/renderablesmallbody.cpp#L285

**Comment by GPayne** [comment]
Pushed fixes for this to issue/1409 branch. This fixes this issue, but more work was done to synchronize changes to UpperLimit, StartRenderIdx, and RenderSize so that changes to one would adjust the other values in the menu. Since these properties are coupled, it's very confusing to the user unless changing one property visually changes the other.
