### ISSUE TITLE
Pausing time through additional scripts in profile not working

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#1418]
Adding `openspace.time.setPause(true)` to additional scripts in the profile leads to Earth being off-focus (not visible) at start-up, and time being set to Sat, 01 Jan 2000.

**Comment by micahnyc** [comment]
I was thinking today that in addition to fixing this, as it should work, it would be nice to have a feature that allows profiles to start paused. I'm thinking this could be a setting for users in the time window of the profile editor.

**Comment by GPayne** [comment]
This problem happens with any time command (setPause, setTime, setDeltaTime) contained in the additional scripts profile section. This is because the additional scripts are executed before the timeManger is properly initialized.
I created issue #1727 to change the way that profiles are initialized, in order to solve this and other problems.

Am currently working on this in branch _feature/profileOverScene_

**Comment by GPayne** [comment]
This is fixed by pull request #1742 which was just merged.
