### ISSUE TITLE
Gaia/Exoplanet conflict in multiwindow setup

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1437]
For example, this issue occurs when using single_gui.xml but not when using single.xml 

Launch with the gaia profile.
Add any exo planet system and visit it. 

Trail is not rendered.

With zone  from issue/1395 then the trail will render, but the zone will not.

I guess the gaia stars are fighting with whatever the exoplanets do last...

**Comment by WeirdRubberDuck** [comment]
The problem seems to be occurring in multiwindow setup for any profile. Tried in the default profile as well and it exists there too

**Comment by WeirdRubberDuck** [comment]
An update on this issue: 
It does indeed seem like whatever scene graph node is added **last** in the exoplanets is not included when using multi-window setup. 

When the star glare from PR #1511, the habitable zone is rendered but not the glare, since that's the scene graph node being added last. 

Note that it makes no difference if the `openspace.addSceneGraphNode(..)` calls are queued independently using `global::scriptEngine->queueScript(..)` once per node, or first concatenated into a big string and added simultaneously using a single `global::scriptEngine->queueScript(..)` call

**Comment by alexanderbock** [comment]
Some more info/braindump:
 - The issue does not show up if the nodes are added through an asset at startup
 - The issue does appear when loaded through an asset via `openspace.asset.add` at runtim
 - It looks like someone is stomping on the VAO of the glare

Thios smells like a OpenGL context handling issue maybe?

**Comment by alexanderbock** [comment]
Yes indeed;  I don't know why it was only the last one that didn't work, but the reason was that the shared OpenGL context in SGCT was only enabled after the presync;  so the images where loaded on the last window's OpenGL context and weren't accessible in the actual rendering window
