### ISSUE TITLE
Move all downloaded data (not tracked by git) to separate folder?

### ISSUE THREAD

**Issue by emiax** [OpenSpace/OpenSpace#150]
Would it make sense to download data files to a separate location than the data folder that is currently being tracked by git? The folder structure could be similar or even identical to the current one, but only containing downloaded resources.

Example:
`data/scene/newhorizons/newhorizons/newhorizons.mod`
`data/scene/newhorizons/newhorizons/newhorizons.data`

`downloads/scene/newhorizons/newhorizons/models/*`
`downloads/scene/newhorizons/newhorizons/textures/*`

Advantages:
- The whole folder could be added to .gitignore instead of individual subfolders in the current (mixed) data folder. 
- Easier to clear the downloaded content: Just delete the folder and fire up the download manager again.
- Switching between branches with different sets of downloaded content will not cause the list of unstaged files to grow like crazy.

Disadvantages:
- Impossible to use relative paths when referencing textures etc.
- Maybe more?

Handling content that is not either handled by git or distrubuted:
When working with large files (volumetric data etc) that are not yet ready to be uploaded to the server or added as torrents, it is possible to keep them local in a separate `devdata` folder, that could also be added to the gitignore.

What do you all think? @alexanderbock @jccosta @GPayne @EricMyers47

**Comment by EricMyers47** [comment]
I've been thinking of something similar, but not directly about git.   I'm imagining installing on Linux using a .rpm or .deb, and there could be several of them.   The basic install would get you the executables and a "starter kit" of data/ for the solar system.   To add more data, you could install more packages.
 
Yes, I know the download manager could also do this, but the point is to make it modular and to allow multiple distribution mechanisms, including the download manager, Linux packages, torrents, or maybe something else.

To do this, does it make sense to break things up as Emil suggests?   Or perhaps to add the additional data packs as submodules (you'd get them all anyway if you clone --recursive).

There's a lot of data, and that's not a big inconvenience if you have a nice internet connection, but if you are trying to install at a school that has limited bandwidth, or a coffee shop, or a dorm that is overloaded because it's close to exams....   Ideally the "starter kit" package would fit on a DVD, so it would also be possible to distribute without a network connection.

This is orthogonal to Emil's suggestion of separate data directories.  You might even have the concept of a DATAPATH  list of the directories where stuff might reside, so you could have several separate directories, but also easily add more if you wish.  That could really help builders and developers.

**Comment by alexanderbock** [comment]
I don't think it is useful to move the downloaded data out of the `data` folder as it would
1. complicate the use of relative file paths
2. increase the number of directories that we need to take care of
3. if people have their own scene modules that does not rely on the launcher to download content, we would split out the application data as our modules would store content in the `download` folder whereas outside modules would store them in place. I think it is more important to keep everything consistent so that internal modules are not distinguishable from external ones.

The cleaning ultimately should be possible through the downloadmanager anyway. It will need a list of downloaded files + version anyway to make sure not to download files that are already current. And if we have that kind of list, it is easy to delete all downloaded files by iterating through that files content.
