### ISSUE TITLE
Anisotropic Mip Maps crash on Intel cards

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#153]
Is it the same bug as the AMD issue?

It crashed in:

``` cpp
            _texture->setFilter(ghoul::opengl::Texture::FilterMode::AnisotropicMipMap);
```

in RenderableRings

and then

``` cpp
            glTexParameteri(_type, GL_TEXTURE_MIN_FILTER, GL_LINEAR_MIPMAP_LINEAR);
            glTexParameteri(_type, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
            glTexParameteri(_type, GL_TEXTURE_MAX_LEVEL, _mipMapLevel - 1);
            glGenerateMipmap(_type);
```

System: Intel HD Graphics 4000 or Intel Iris Pro Graphics 580

**Comment by jonathanbosson** [comment]
I've tried to debug this error in CodeXL to figure out what generates the crash. 
I don't have a fix for it yet, but in the function call glGenerateMipmap(_type) we get a second chance exception due to access violation.

> The thread tried to read or write data that is misaligned on hardware that does not provide alignment. For example, 16-bit values must be aligned on 2-byte boundaries; 32-bit values on 4-byte boundaries, and so on.

**Comment by jonathanbosson** [comment]
Fixed issue with commit [bc12500ea71c43291de5c12d4d794ada5cffcb11](https://github.com/OpenSpace/Ghoul/commit/bc12500ea71c43291de5c12d4d794ada5cffcb11)

**Comment by EricMyers47** [comment]
This is still present in the current master branch and should be fixed there.

**Comment by kbladin** [comment]
One thing I am not sure is considered: Generating mipmaps should only be done when the texture has been uploaded to the GPU. It might be a good idea to ensure that it is uploaded before calling glGenerateMipMap. That of course should be the case for both anisotropic and standard mipmaps.

**Comment by jonathanbosson** [comment]
What's the status on this issue? 
I have not had problems with my Intel card since commit [bc12500](https://github.com/OpenSpace/Ghoul/commit/bc12500ea71c43291de5c12d4d794ada5cffcb11),

**Comment by kbladin** [comment]
How does the bug manifest itself (or has been)? Does it crash as soon as the function is called or is it a bit seemingly random? I have experienced some weird crashes on my mac as well (NVIDIA GeForce GT 650M) but only sometimes.

It happens both on `glGenerateMipMaps` and on `glGetQueryObject` (called from SGCT). If it is the same issue I don't think it is there the problem is. I even got crashes on `glGetQueryObject` when I turn off mip maps. It happens mostly when the program works hard, for examples when globe browsing using many layers but a couple of times it has crashed on startup as well. We have had some performance issues on the dome in Nkpg as well and I'm starting to think that it might be related. Maybe also to the recent issues in the Hayden dome..

**Comment by emiax** [comment]
@EricMyers47, can you confirm that this is still happening in the master branch? As far as I can tell, the fix was already pushed to master when you noticed that it was not working. Could it be that this solution only fixed the issue on Intel cards and not AMD cards? Can you give the specs of the machine where it fails?

**Comment by jonathanbosson** [comment]
@kbladin for me the application used to crash on startup on trying to render Saturn's rings, which is the first time the `glGenerateMipmap(_type);` is called.

**Comment by EricMyers47** [comment]
Right now I don't get any graphics on Master, both Windows and Mac.   It may be that I cannot complete the Sync Step, not the graphics cards.

**Comment by emiax** [comment]
@EricMyers47, to be sure what causes the crash, you can fire up the debugger and check the stack trace when the crash happens.

**Comment by alexanderbock** [comment]
It ended up being an issue with missing setup for the textures before the anisotropic upload.  Nvidia was more lenient regarding the OpenGL standard;  Intel wasn't.  The state has in the meantime been added, so it doesn't crash anymore either
