### ISSUE TITLE
Globelabels are making the stars shine through the planet

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#1610]
When enabling the globe labels, the background RenderableStars are rendered on top of the labels, maybe an issue with writing the position in the g buffer?

https://user-images.githubusercontent.com/4921724/119635630-2d166d80-be14-11eb-966f-8cd604ffc0c6.mp4

**Comment by WeirdRubberDuck** [comment]
Saw this problem too. Note that it only happens when the opacity of the labels is less than 1.0, in which case we normally (for renderables, that is) switch the render bin from `Opaque` to `PreDeferredTransparent`. This is not being done for the Globe labels, as the class `GlobeLabelsComponent` is not a Renderable, and the labels are always being rendered in the `Opaque` bin

Maybe switching the render bin would solve the problem?

**Comment by alexanderbock** [comment]
Yea, I think it would solve the problem
