### ISSUE TITLE
Earth horizions data not matching spice data

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1626]
While it is known that they would have different precision, the horizons trail seems off by a large amount that may indicate an incorrect assumption in our formula for processing the data. 

[earthhorizons.zip](https://github.com/OpenSpace/OpenSpace/files/6580726/earthhorizons.zip)

**Comment by micahnyc** [comment]
It's us unknown if the calculation is wrong, if the data is being used with out the correct precision....maybe we need to account for other variables in their data set such as range-rate or something else.

**Comment by Roxeena** [comment]
Some screenshots:

![horizons_earth2](https://user-images.githubusercontent.com/16215103/121051321-a79ea000-c7b9-11eb-8fe6-384112100cca.png)
![horizons_earth1](https://user-images.githubusercontent.com/16215103/121051327-a8373680-c7b9-11eb-801a-e30ed358a9f8.png)

**Comment by alexanderbock** [comment]
Not sure if this is related, but I saw this today as well..  The position of the ISS trail is different from the trail shown by the "status" from `data/assets/scene/solarsystem/planets/earth/satellites/misc/tle-new.asset`

![OpenSpace_000000](https://user-images.githubusercontent.com/4921724/121155090-c6e40e80-c847-11eb-8093-cdcc9ba48ac9.png)

**Comment by GPayne** [comment]
I checked the ISS vs the tle-new trail on my computer, and saw the same trail "shadowing" the ISS. The _tle-new_ file from celestrak has these 2 entries with identical positions:
SOYUZ-MS 18             
CREW DRAGON 2           
which are the Russian and U.S. capsules both launched recently to the ISS. I guess celestrak doesn't update their position as much as they do with the ISS.

A trick for figuring out which satellite is which in a TLE file with multiple satellites: You can selectively display one at a time and a log entry will show the satellite name, as described here:
http://wiki.openspaceproject.com/docs/components/satellites#selectively-rendering-individual-satellites-in-a-group

Unfortunately this doesn't help solve the horizons data mismatch, but I'll spend some time looking into that.

**Comment by GPayne** [comment]
**Update #2**
The "offset circles" variation in orbits reminded me of the sun barycenter motion, so I created a new horizons data file using the same steps at:
http://wiki.openspaceproject.com/docs/builders/ephemeris/horizons#downloading-ephemeris-data-from-jpl-horizons-site
but instead, chose observer = sun (@10) rather than the solar system barycenter (@0). I tested the result and the trails line up perfectly (the position lags behind by about 1 earth radius for some reason). This is using the same asset file setup (attached) as before, which uses the OpenSpace SolarSystemBaryCenter as the parent.

Micah's original horizons file above is correct, in the sense that it has the configuration that _should_ work. In my first attempt I went through the wiki steps and got the same result as shown in the pictures above.

It's nice that it lines up this way, but I still don't know why choosing the sun(10) as the observer makes it work.

[earthhorizons_gene.zip](https://github.com/OpenSpace/OpenSpace/files/6621006/earthhorizons_gene.zip)

**Comment by alexanderbock** [comment]
Good catch!  I think i found the culprit:
https://github.com/OpenSpace/OpenSpace/blob/master/data/assets/scene/solarsystem/planets/earth/transforms.asset#L14

The `EarthBarycenter` node is parented to the Solarsystem barycenter but its `SpiceTranslation` uses "SUN" as the observer..  so teh Horizons position is actually correct and the Spice one isn't

**Comment by Roxeena** [comment]
Alex and I did some more digging on this and we figured out that our Spice kernels don't explicitly include the SSB, meaning every time you try to use a spice translation with “SSB” only (0, 0, 0) is returned and your trail doesn’t show up. This is probably the reason why “SUN” is used almost everywhere when it should be “SSB” instead. But somehow the SSB kernel is included implicitly by Spice since it can still be used if the function `hasSpkCoverage` is changed to always return true for that special case. This also means that the nodes `SunIAU` and `SunECLIPJ2000` in the Sun `transforms.asset` end up at the same place (0, 0, 0) as the SSB, so our Sun is not placed correctly either.
