### ISSUE TITLE
Modelprojection is using the wrong textures for projections in OSIRIS-REx profile

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#1652]
With simulation speed at ~1 year per second, around the time of OSIRIS-REx’s
rendezvous with Bennu, Bennu became completely covered in OSIRIS-REx’s surface
textures (see image below).

![image](https://user-images.githubusercontent.com/4921724/122183190-48aceb00-ce8b-11eb-9a35-f77c0cd9e6d5.png)

-- As reported by Alex E. --

**Comment by GPayne** [comment]
I am unable to reproduce this problem.
I've looked at the model files for a mixup in their .mtl (material) file references but I haven't found anything.
I've looked at the asset files to see if they are using the wrong model files are texture files; no problems found.

I looked closely at the image projection sequences, since image files are projected onto the surface. One way this kind of thing could happen is if a texture file from one directory accidentally found its way into the wrong directory. I checked that the Utah server doesn't have this problem, and it doesn't appear that the Sweden server does. I tried to recreate such an error by copying the osiris-rex probe texture file into the directories for the approach & orbit image sequences (doing this in both my sync and cache directories) but couldn't reproduce it.

I assume this is the latest master branch? I'm asking because in an earlier (now deleted) branch I purposely added this texture to a Bennu model when trying to troubleshoot the rendering.
