### ISSUE TITLE
Create color helper util asset

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1658]
This asset would export color values and/or color files based on existing lua script.

example use
colorHelper.getColorFile("pink")

When done, replace/delete data/colors/pink.png used in orionnebula.asset

**Comment by alexanderbock** [comment]
I don't think we need separate assets for it;  the `openspace.createSingleColorImage` function should do the same trick.

so in  that case it would be:
`local path_to_file = openspace.createSingleColorImage("pink", {1.0, 0.0, 1.0})`

and the function also caches the results, so calling the function from multiple assets ought to work as well

**Comment by alexanderbock** [comment]
Is this correct @WeirdRubberDuck ?  If so, could you replace the one in orionnebula and close the ticket?

**Comment by WeirdRubberDuck** [comment]
That is correct. And I even think it's better because it makes it more apparent what exact color "pink" represents (note that `{1.0, 0.0, 1.0}` would be magenta and not the pale pink color in the texture)

I'll remove the file, but seems like the asset has been updated to not use it already (probably with the model loading updates)
