### ISSUE TITLE
Idle behavior should happen when idle

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1730]
Right now the orbital navigator's idle behavior is only happens if you explicitly trigger it. 

Expected functionality would be to have an idle timer which triggers it after no interaction happens for the specific duration.

**Comment by micahnyc** [comment]
Perhaps this should use the interaction monitor? 

Or events? Setup interaction monitor to dispatch an idle event, then bind apply idle behavior to the event.

**Comment by liuloppan** [comment]
The Interaction monitor was made explicitly to be able to have an 'idle mode'. We use it on our touchtable application for Vislabs.
In our case we only use subscription to property values via the WebApi and can find out when it goes idle that way. Considering the many use cases of OpenSpace it is good if the idle behavior can be easily tweaked, I like the idea of event-binding.

**Comment by WeirdRubberDuck** [comment]
I'd happily have a discussion about this. The reason I didn't implement it using the interaction monitor was a distinguishment between "user interaction" and "camera interaction". User interaction can be any interaction that involves a mouse click or any other kind of user input, and camera interaction involves the user somehow controlling what the camera does/how it moves. 

Simply put: I wanted the "idle behavior" to keep happening when interacting with the UI menus, but stop as soon as the user tries to navigate somewhere else.  To be able to use the InteractionMonitor for this, it would have to distinguish between these two kinds of interactions somehow. But I agree that it would  be nice to come up with a solution so that it starts automatically after a certain amount of time, if no navigation has occurred

**Comment by alexanderbock** [comment]
Could be implemented using #1833
