### ISSUE TITLE
Failure to complete initial syncing process

### ISSUE THREAD

**Issue by noahdasanaike** [OpenSpace/OpenSpace#179]
There appears to be a server-side issue pertaining to the initial syncing of scene data, in which the command-line interface halts the downloading process at varying points. 

Two devices were used for testing to ensure that the issue was not unique to an individual computer. Upon opening task manager, the launcher observably accounts for 0 Mbps of network activity. 

If the initial syncing process is attempted to be bypassed and the user launches OpenSpace, the window fails to start-up properly and freezes. 

Both devices used for testing were running Windows 10 - one of them had already successfully synced all data months prior, but when everything was rebuilt and the syncing process attempted within the past week, it too failed. 

The LauncherLog for one device has been attached below, but there appear to be no reported anomalies - the last row is merely where the syncing process stopped on the most recent attempt. The process continuously halts upon encountering .bsp files - perhaps there is an issue with the torrent server?

[LauncherLog.html.pdf](https://github.com/OpenSpace/OpenSpace/files/695146/LauncherLog.html.pdf)

The version of OpenSpace on which this issue occurs is the most recent master (commit dbe46b8).

**Comment by EricMyers47** [comment]
I had similar experience on Windows 10 but it turned out that it was just really, really slow, and the sync did complete after about 2 days.   Alex seemed to think this was a bug in how all the transfers are logged and how the logging uses (or mis-uses) threads.
Perhaps you could try running it and leaving it to confirm my observations?
Did you build the master branch with Debugging or Release?  The hope is building a Release version would not have this problem, but I've not tested that yet.
Thank you for your observations.

**Comment by noahdasanaike** [comment]
That's what I thought originally as well, but the issue has persisted beyond two days. I'm running on release.

**Comment by noahdasanaike** [comment]
Thought I would point out that the issue is still occurring, and is prohibiting installation at the Raleigh Museum of Natural Sciences.
