### ISSUE TITLE
Labels seem to have the wrong depth

### ISSUE THREAD

**Issue by Roxeena** [OpenSpace/OpenSpace#1915]
In the JWST profile the labels for L1, L2 and JWST are rendered in the wrong depth order, see video. The label for L2 should be closest to the camera in the video and L1 furthest away but it seems like JWST is closest and L2 is furthest away.

https://user-images.githubusercontent.com/16215103/159302880-5ba103e0-c073-4dff-bb65-5749be78f073.mp4

**Comment by alexanderbock** [comment]
Could it be that they are rendered without depth testing at all?

**Comment by Roxeena** [comment]
Switching [this line](https://github.com/OpenSpace/OpenSpace/blob/f7d3d3bad1f2a714874a100d56322fd53b9d99a4/modules/base/rendering/renderablelabels.cpp#L387) from `false` to `true` seems to solve the issue. Was there a specific reason why this was set to `false` in the first place?

**Comment by WeirdRubberDuck** [comment]
That line disables the depth testing, to that makes sense :) 

Not sure why it was set to false, but a guess would be to make the label show up in front of planet, even if it's position is set to be inside the planet. That part of the code hasn't been changed since the label for Earth was added, so maybe you could try enabling that label and see how it looks like?

If there are no visual problems with the Earth label, or the other planets, I'd say go ahead and change it. And if there is, maybe we could fix it some other way

**Comment by WeirdRubberDuck** [comment]
Also, if you go ahead and change it, maybe you could also replace[ line 424 and 425](https://github.com/OpenSpace/OpenSpace/blob/f7d3d3bad1f2a714874a100d56322fd53b9d99a4/modules/base/rendering/renderablelabels.cpp#L424) with: 

```
    // Restores GL State
    global::renderEngine->openglStateCache().resetBlendState();
    global::renderEngine->openglStateCache().resetDepthState();
```

To correctly restore the states #1420

**Comment by alexanderbock** [comment]
Can this be closed?
