### ISSUE TITLE
Harmonizing the Ra/Dec specification

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#2026]
The JWST pointing webpage and the Skybrowser use Ra/Dec in different units (degrees vs h, m, s)

**Comment by ylvaselling** [comment]
Which standard should we have?

**Comment by alexanderbock** [comment]
Personally, I would argue for degrees, but if you and @Roxeena agree on one format, go with that instead

**Comment by Roxeena** [comment]
I think for the web page it makes more sense to get it in h, m, s since the user might find the coordinate themselves by googling it and then it is most common to find it in that format. But the event for pointing JWST in OpenSpace will use degrees instead since that will get the coordinates from Skybrowser that uses degrees. But I have a conversion function from h, m, s in the web page if we want to support both I can just copy that to OpenSpace as well.

**Comment by Roxeena** [comment]
The JWST pointing website now supports both formats. Close this?

**Comment by alexanderbock** [comment]
:+1:
