### ISSUE TITLE
Gaia errors when loading data

### ISSUE THREAD

**Issue by Roxeena** [OpenSpace/OpenSpace#2054]
Two datasets in the Gaia profile have issues with loading on start up. They don't show up when enabled in the GUI later either.

![gaia-errors](https://user-images.githubusercontent.com/16215103/165723778-e560f6a1-3ad4-401e-accf-d38677f8dcd4.png)

**Comment by WeirdRubberDuck** [comment]
This check was added recently, as a result fo our speckloader not being able to read non-number values: https://github.com/OpenSpace/OpenSpace/commit/86dcff62c4563f958fbf3ff28e5511ea6f35daef

This smells like bug to me though, because when quickly looking at GaiaAbundApogee.speck, there are no non-number data variables
