### ISSUE TITLE
Unit tests give out error message in the log

### ISSUE THREAD

**Issue by ylvaselling** [OpenSpace/OpenSpace#2109]
On the master branch, the unit tests for OpenSpace are passed but there are error messages printed out. The error message is the following: 

![image](https://user-images.githubusercontent.com/24265984/168140410-ab453884-a528-4bd7-be3a-55342f938ebd.png)

**Comment by WeirdRubberDuck** [comment]
Those errors are intentional. There are test cases that check "faulty" inputs to property values. [Here's one eample](https://github.com/OpenSpace/OpenSpace/blob/5877112103cdcb894695c214c21c15d2625fbe0b/tests/property/test_property_listproperties.cpp#L199)

I do however agree that it can be a bit confusing that the messages appear in the log

**Comment by alexanderbock** [comment]
One solution could be to set the unit test log verbosity to only show Fatal errors

**Comment by alexanderbock** [comment]
Closing this as a wontfix since with a change it would be very hard to determine what the reason for a failing test would be if we don't have any error messages
