### ISSUE TITLE
Disabling modules does not affect the CMake configuration

### ISSUE THREAD

**Issue by danielk333** [OpenSpace/OpenSpace#2120]
<< Description of the problem >>

disabling `WebBrowser` in `openspace.cfg` with
```
    WebBrowser = {
        Enabled = false
    },
```
seems to not disable CMake configuration of this module

<< What did you expect to happen >>

CMake would not configure this module.

<< What did happen? >>
```
RRORLinux is not yet supported for Web Browser Module.
-- --- End: Application: OpenSpace ---
-- **** End: Configuring Applications ****
-- **** Generating OpenSpace unit test ****
ERRORLinux is not yet supported for Web Browser Module.
-- ======= END: CONFIGURING OPENSPACE PROJECT =======
-- Configuring incomplete, errors occurred!
```

Is there a standard way of disabling modules? I could not find any in the wiki or readme's. 

It seems there is a standard way of disabling submodules as mentioned in #2110

**Comment by danielk333** [comment]
I also tried to remove `Web Browser` and `skybrowser` completly, folders and configuration and all, but it still throws an 
```
CMake Error at modules/CMakeLists.txt:130 (message):
  Could not find dependency webbrowser for module skybrowser
Call Stack (most recent call first):
  modules/CMakeLists.txt:119 (get_recursive_dependencies)
  modules/CMakeLists.txt:235 (get_recursive_dependencies)
```
So it seems that the module system is clean for additions but not for removal right now

**Comment by GPayne** [comment]
The standard way to disable a module is to disable the corresponding CMake variable, using either the **ccmake** or **cmake-gui** applications. Inside, you will see a list of `OPENSPACE_MODULE_*` variables for each module.
Your attempt to delete module folders didn't work because of module(s) needing those as dependencies.

You're right that this isn't well documented; it's not something that people should normally have to do. The reason it was necessary for you in this case was the recent addition of the SkyBrowser module which depends on the WebBrowser module (which disabled in linux).
However, the good news is that the fixes for this on linux have just been merged into the master branch, so if you do a fresh clone of master, everything should work for you now.

**Comment by danielk333** [comment]
Ooooh awesome, going to try it out now, ill be back.

Also adding a short comment in the docs about the `OPENSPACE_MODULE_*` is a good idea i think, since for starting out developers disabling modules seems quite useful.

**Comment by danielk333** [comment]
Great! Now the CMake command runs and generates the `ninja` config so ill close this for now.

The build still fails though with the same problem in the `assimp` submodule. Ill post about that in #1747 though since that has the same error message.
