### ISSUE TITLE
Load navigation state in profile not working as expected

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2143]
When using the Navigation portion of the Camera box in the profile editor, the camera on startup is not in the correct place.

Presumably an issue with the time or delta time on startup. 

As reported here: https://team-openspace.slack.com/archives/C9RBB2XJP/p1655142986980109

**Comment by WeirdRubberDuck** [comment]
A little brian dump before I go about fixing this: The main problem seems to be different decisions about how to handle missing values for the reference frame. 

When read from a dictionary, the navigation state uses the anchor if no frame is specified
https://github.com/OpenSpace/OpenSpace/blob/c95dcee99ee34dab207f7e1818c6b74423d220ea/src/navigation/navigationstate.cpp#L71

But when loading from a profile, "Root" is used
https://github.com/OpenSpace/OpenSpace/blob/c95dcee99ee34dab207f7e1818c6b74423d220ea/src/engine/openspaceengine.cpp#L1719


In addition, something that I find a bit confusing is that we also make a hidden decision about which frame to use based on how close we are to the current anchor
https://github.com/OpenSpace/OpenSpace/blob/c95dcee99ee34dab207f7e1818c6b74423d220ea/src/navigation/navigationhandler.cpp#L372


I can see why this decision was made, but it does not work very well for nodes without bounding spheres (such as the ISS noed), and the varied behavior could potentially be confusing to users. Also, when using Root as reference frame, the resulting navigation state will make sense if and only if the simulation time is exactly the same when applying the navigation state again. That is, more often it makes sense to use the current Anchor node as the reference frame, because then at least that node will be in the same position when the navigation state is reapplied, even if the simulation time does not match. 

For the reason above, my suggestion would be to change it so that the Anchor node is always used as reference unless something else is specified.

**Comment by WeirdRubberDuck** [comment]
However, still have to test this theory out. We might also have a problem with the delta time
