### ISSUE TITLE
Hover Circle if too visible

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#2153]
When working on the new Juice profile, the HoverCircle becomes visible while inside the solar system:

Thin white line on right 5th of the screen
![image](https://user-images.githubusercontent.com/4921724/174593836-1e08b241-eaaa-4019-9517-495c28cab8a3.png)

**Comment by WeirdRubberDuck** [comment]
I could probably give this a look, since I implemented the fading behavior for the hover circle. However, I'm not quite sure how to reproduce it

(Also note that I would want to rename it to "hover indicator" or something, since it does not necessarily have to be a circle. The texture can be replaced with whatever 🙂 )

**Comment by alexanderbock** [comment]
:+1:  Sounds good.  I think it might be that we'd want to toggle the "enabledness" of the Hover Circle to whether currently a SkyBrowser instance exists or not
