### ISSUE TITLE
Retrieve GIBS datasets for lodearth automatically

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#222]
Using the sources provided GIBS

https://wiki.earthdata.nasa.gov/display/GIBS/GIBS+Available+Imagery+Products#expand-CorrectedReflectance16Products
https://wiki.earthdata.nasa.gov/display/GIBS/GIBS+API+for+Developers#GIBSAPIforDevelopers-Script-levelAccessviaGDAL

it is possible to write a Lua script that will generate the XML files to add any layer to the Earth that is available in Worldview

**Comment by alexanderbock** [comment]
From Ryan Boller: 
are you looking for the colormap XML files?  If so, a likely starting point will be the GIBS WMTS GetCapabilities document:
http://gibs.earthdata.nasa.gov/wmts/epsg4326/best/1.0.0/WMTSCapabilities.xml

Within that document you’ll find links to colormaps for individual layers, e.g.:
https://gibs.earthdata.nasa.gov/colormaps/v1.3/AMSR2_Snow_Water_Equivalent.xml

You can also scrape the colormap directories, though it’s not something that we advertise or support (e.g. it may not be available in the future… though it very well may be :):
https://gibs.earthdata.nasa.gov/colormaps/

Some more background on the GIBS API page:
https://wiki.earthdata.nasa.gov/display/GIBS/GIBS+API+for+Developers#GIBSAPIforDevelopers-ImageryAPI/Services

**Comment by kbladin** [comment]
It is possible to programatically add layers using `openspace.globebrowsing.addLayer`. Also I added the ability to create GDAL WMS specifications for temporal and standard GIBS datasets using lua functions.

It is not done automatically though. We should have a way of listing all datasets given a WMS capabilities document. We need to be able to get all the required parameters for that dataset. Not sure if it can be done so general so that we do not need to consider that they are GIBS datasets, and that GDAL automatically creates its specifications. Might be hard for temporal datasets though and I am not sure how much GDAL can do automatically. Otherwise we can write a converter from the layer in the capabilities document to the GDAL specification and use that, fetching the layer only using its name.

How do we make HTTP requests so that we only need to provide a link to the capabilities document? Is it using curl? Do we have a function for that in place, taking a link and returning a string?

**Comment by alexanderbock** [comment]
Yes, that would be DownloadManager::fetchFile

**Comment by kbladin** [comment]
What I think should be done here is a class that performs the fetching given a path to a getcapabilities page. It should be "global" in the sense that there is one instance of it per globe browsing module. This class can have script functions for getting all layer names, get a wms specification given a layer name and perhaps also some interfacing to create actual layers from these specifications. It would be nice if it had its own GUI component but it might also be possible to use properties to for example list layer names etc. These will then be place under the globebrowsing modules properties.

At initialization there could be lua function calls to load wms capabilities pages, something like
```lua
openspace.globebrowsing.wms.getWMSCapabilities("http://gibs.earthdata.nasa.gov/wmts/epsg4326/best/1.0.0/WMTSCapabilities.xml")
```

And then all the layer names should be displayed in a list. Then one could call:
```lua
wmsSpec = openspace.globebrowsing.wms.getWmsSpecification("nameOfLayer") -- "nameOfLayer" can perhaps also be replaced with some identifier, wmsSpec is a string
```

And then to create a layer:
```lua
layerSpec = { Name = "nameOfLayer", FilePath = wmsSpec }
```

Add the layer:
```lua
-- This function is already implemented
openspace.globebrowsing.addLayer("Earth", "ColorLayers", layerSpec)
```

Then of course it would also be nice to add these functionalities as GUI components for this class as well.
