### ISSUE TITLE
Get Texture Image Loading working well on linux

### ISSUE THREAD

**Issue by GPayne** [OpenSpace/OpenSpace#233]
I've had problems using **FreeImage** for texture images on Ubuntu linux. I tried the **SOIL** library but its planetary textures are flipped horizontally. I tried the **devIL** library but it was unable to load images. One other developer has had similar problems but on OpenSUSE linux.
The objective here is to get one of these options working reliably.

**Comment by codingInSpace** [comment]
Hi Gene, did you get wiser on this? /new thesis student

**Comment by GPayne** [comment]
Hi Jonathan, no I never got this working, and since Windows was the main platform for OpenSpace, I set it aside to do other things. If you are interesting in working on this, let me know and I'll share the info I have where I left off.

**Comment by GPayne** [comment]
This is from almost a year ago, so a lot of things may have changed; it might even just work now? I was testing this on Ubuntu 16.04. Here's a summary:
1. FreeImage: I wanted to use this as the default texture library, but it failed to show any textures on planets. I tried the latest version of the library as well as older versions, and libfreeimage as well as libfreeimageplus, but no luck.
2. DeVIL: I tried version 1.7.8, but OpenSpace reported a lot of texture errors (many more than with FreeImage). I was planning on trying the latest version (v1.8), which is where I left-off.
3. SOIL: I recall having problems with SOIL-equivalent call to FreeImage_FlipVertical() in the openspace texture loader code.

**Comment by codingInSpace** [comment]
Well I am running arch linux (should be similar enough) with the latest FreeImage package (3.17) and the planet textures indeed do not show, but they do show for the sun which is a RenderablePlanet and not a RenderableGlobe, and for other things like RenderablePlanes. 

For the planets it throws errors like:
```bash
Failed to load dataset: /home/jonathan/Code/OpenSpace/data/assets/scene/solarsystem/planets/mercury/map_service_configs/Utah/MessengerMDIS.wms

Failed to load dataset: /home/jonathan/Code/OpenSpace/sync/http/venus_textures/1/venus.jpg
```
("dataset", not texture)

So the case where the textures fail is for RenderableGlobes. Does it not mean the FreeImage lib is probably fine but something in the source fails for linux when it comes to the LODded globe dataset loading?

I probably do not have the knowledge to manage to fix this in the near future but I will probably look into it going forwards because I would love to run OpenSpace on linux as well 👍 Thanks

**Comment by GPayne** [comment]
I ran FreeImage 3.17 as well. The symptoms you describe sound similar to what I saw.
I agree that FreeImage lib is fine but something in the OpenSpace texture handling code that causes the problem.
Are you looking at this because you want to run on linux, or were you assigned this issue (just asking to get an idea of the priority)?

**Comment by codingInSpace** [comment]
I see. No I would simply enjoy running it on Linux as I much prefer to use it personally, but starting February I will likely work in a Windows environment for the thesis project. So it is not an immediate priority :) We should try to fix it when we have time.

**Comment by PjotrSvetachov** [comment]
I also have this problem. It appears OpenSpace tries to use gdal to open the database. If I add the gdal error to the print statement I get the following: "libjpeg: JPEG parameter struct mismatch: library thinks size is 600, caller expects 632". It might be that two different jpeg libraries are compiled against and that because of that there is a conflict?

**Comment by PjotrSvetachov** [comment]
Ok I found the problem: sgct uses libjpeg-turbo and this conflicts with the jpeg library that gdal is using. I found this workaround:

- Remove turbojpeg-static from apps/OpenSpace/CMakeLists.txt
- Add turbojpeg-static to apps/OpenSpace/ext/sgct/CMakeLists.txt on line 443
- Add to apps/OpenSpace/ext/sgct/CMakeLists.txt the following:
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wl,--exclude-libs,ALL")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wl,--exclude-libs,ALL")

**Comment by sovanny** [comment]
I have the same problem, on Ubuntu 16.04.

At first, the application didn't get passed the loading screen as the logo image failed to load. Solved it by changing the order of the if-statements in renderengine.cpp, so that the #ifdef GHOUL_USE_STB_IMAGE block is the first one in order, followed by SOIL (not sure if the latter made a difference).

But still have the problem with the texture on the planets. Getting errors like

`Failed to load dataset: /home/shuynikk/Thesis/OpenSpace/sync/http/venus_textures/1/venus.jpg`

Tried @PjotrSvetachov 's solution but nothing changed. I did:

- Removed  turbojpeg-static on line 115, also removed line 138; set_folder_location(turbojpeg-static "External/SGCT") in apps/OpenSpace/CMakeLists.txt
- Added  turbojpeg-static to target_link_libraries on line 443 in apps/OpenSpace/ext/sgct/CMakeLists.txt . Added the two set() lines.

Did you also remove something from apps/OpenSpace/ext/sgct/CMakeLists.txt ?

**Comment by sa5bke** [comment]
(I wrote about this in the slack #linux channel, but as it is about this issue I thought better add it here too.)

I have been testing out OpenSpace on Ubuntu 18.04 for the last couple of days and my conclusion right now is that `jpeg` does not work at all in my installation. I have tried to test the different render engines by commenting them out, but no luck. `png` works so I have been able to convert jpg to png and change the asset files. Also WMS (gdal) work by updating the URL and use png instead of jpg. 

I think it has something to do with the Openspace is being linked to the locally installed turbojpeg that is newer than the turbojpeg library that is included in OpenSpace (used on Windows I assume), but somehow gives this incompatibility. See below:

```
esn@t20:[/home2/esn/OpenSpace/bin]: ldd OpenSpace | grep jpeg
        libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007f0107efe000)
        libjpegxr.so.0 => /usr/lib/x86_64-linux-gnu/libjpegxr.so.0 (0x00007f010228a000)
esn@t20:[/home2/esn/OpenSpace/bin]: dpkg -L libjpeg-turbo8 | grep libjpeg.so.8
/usr/lib/x86_64-linux-gnu/libjpeg.so.8.1.2
/usr/lib/x86_64-linux-gnu/libjpeg.so.8
esn@t20:[/home2/esn/OpenSpace/bin]: dpkg -l | grep libjpeg-turbo8:amd64
ii  libjpeg-turbo8:amd64                                        1.5.2-0ubuntu5.18.04.3                          amd64        IJG JPEG compliant runtime library.

```
OpenSpace/sgct includes 1.4.1 version of turbojpeg. I also tested to workaround suggested by @PjotrSvetachov and also tested by @sovanny but it did not work for me. I found the `issue/233b` branch that uses another branch of sgct that has removed turbojpeg completely. So it looks like you are working on this , so I guess no need for me to do any more trouble shooting on this. 

What is the  status of issue/233b branch? I actually compiled it and run it but "everything" is black, the GUI works but no assets are shown. So before I continue with that, it would be interesting to hear about what I could expect of it right now. Maybe not ready for end user or do you want us to try it? I would like to give feedback if you want. I am also working on packaging OpenSpace as a flatpak: https://github.com/sa5bke/flatpak-openspace which also has this jpg-problem.

**Comment by GPayne** [comment]
The issue/233b branch works on Ubuntu 18.04. The sgct submodule version it references uses the STB library for textures, and it worked well. Everything including textures was working for me except the web GUI (the F1 imgui works however). At least, it did work (e.g. commit f6dcbd9) but I haven't kept up with the latest changes. @alexanderbock has been adding to the issue/233b branch for a lot of new commits relating to his sgct refactoring. So, this branch is no longer limited to this linux issue. I had been planning on closing issue 233 when this branch is merged into master.

**Comment by sa5bke** [comment]
Thanks! It works. I was greeted with an Earth looking like it should for the first time ever since starting to play with OpenSpace around 1 year ago. I did not have access to my Ubuntu box but tried this on a Red Hat Entprise Linux using Nvidia VGPU. Worked in that environment too after applying a patch for the usage of xferinfo in curl. I already have a PR for that: https://github.com/OpenSpace/OpenSpace/pull/1037

But I had another problem and now with `libpng warning: Application built with libpng-1.5.13 but running with 1.6.17`. I solved this by changing cmake to find to local PNG library and link OpenSpace against it instead of the included static one. I will look into a PR for this too.

Thanks again for this fanastic tool which also now seems to be able to be useful to the full extent on different Linux OS.

**Comment by sa5bke** [comment]
I have now compiled https://github.com/OpenSpace/OpenSpace/commit/f6dcbd99d8c614f082f43b0aa889f5497c24cd90 and it works great also on my Ubuntu 18.04. I then tried the rest of the commits in that branch: https://github.com/OpenSpace/OpenSpace/commits/issue/233b . All commits from https://github.com/OpenSpace/OpenSpace/commit/f6dcbd99d8c614f082f43b0aa889f5497c24cd90 until https://github.com/OpenSpace/OpenSpace/commit/94e150f0720ea2699911b94b535adc2cbada3780 does not build. https://github.com/OpenSpace/OpenSpace/commit/94e150f0720ea2699911b94b535adc2cbada3780 builds but gives the issue with "black screen" on my system. I also tried some newer commit (https://github.com/OpenSpace/OpenSpace/commit/f434ef4261a2f4b06f38642207f7944071c58c46)  but it also has this issue. I included a screenshot of the issue.
![openspace_94e150f0720ea2699911b94b535adc2cbada3780](https://user-images.githubusercontent.com/1207291/71725481-5952d800-2e34-11ea-9e96-7144b4bc6928.png)

**Comment by GPayne** [comment]
@sa5bke, can you post the line from your openspace.cfg file that sets `SGCTConfig`? And if you are using a custom SGCT configuration file, please post that as well.

**Comment by sa5bke** [comment]
I use the default settings, no changes made from what is in the repo: `SGCTConfig = sgct.config.single{} ` but just to test i tried also `SGCTConfig = "${CONFIG}/single_gui.xml"` and now one black screen (where rendering should go) and one for the GUI.

**Comment by GPayne** [comment]
OK, thanks for posting. If you are running that default SGCT config, then that shouldn't be a problem. Could you email me your log output (my profile email)?

**Comment by jichengtao** [comment]
> I have now compiled [f6dcbd9](https://github.com/OpenSpace/OpenSpace/commit/f6dcbd99d8c614f082f43b0aa889f5497c24cd90) and it works great also on my Ubuntu 18.04. I then tried the rest of the commits in that branch: https://github.com/OpenSpace/OpenSpace/commits/issue/233b . All commits from [f6dcbd9](https://github.com/OpenSpace/OpenSpace/commit/f6dcbd99d8c614f082f43b0aa889f5497c24cd90) until [94e150f](https://github.com/OpenSpace/OpenSpace/commit/94e150f0720ea2699911b94b535adc2cbada3780) does not build. [94e150f](https://github.com/OpenSpace/OpenSpace/commit/94e150f0720ea2699911b94b535adc2cbada3780) builds but gives the issue with "black screen" on my system. I also tried some newer commit ([f434ef4](https://github.com/OpenSpace/OpenSpace/commit/f434ef4261a2f4b06f38642207f7944071c58c46)) but it also has this issue. I included a screenshot of the issue.
> ![openspace_94e150f0720ea2699911b94b535adc2cbada3780](https://user-images.githubusercontent.com/1207291/71725481-5952d800-2e34-11ea-9e96-7144b4bc6928.png)

Hi @sa5bke , have you solved the "black screen" problem? I encountered the same issues with you when I run the latest (0.15.1) version under Ubuntu 18.04.

**Comment by GPayne** [comment]
The blank screen rendering at the end of this issue has been moved to issue #1163
