### ISSUE TITLE
Use the idle/interaction detection to cancel the countdown for exiting

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2393]
To make it a bit harder to quit openspace by accident, we could make it so that when the countdown is going, if you use the mouse to control the camera, it cancels the countdown.

**Comment by alexanderbock** [comment]
Include any keyboard interaction to abort the shutdown

**Comment by alexanderbock** [comment]
Adding the default countdown to 5 seconds?

**Comment by alexanderbock** [comment]
Only _clicking_ with a mouse would abort the countdown

**Comment by hedbergj** [comment]
Just for feedback purposes, this is now borderline annoying when building assets (i.e. requiring a lot of restarting OS), since now you have to wait the whole 3 seconds before alt-tabbing to a different application or else it cancels shutdown. I'll reduce the shutdown wait to alleviate the issue I guess? But it does make me wonder why can't OS just behave like normal software and require a 2-key combo to quit?

**Comment by alexanderbock** [comment]
On Windows Alt+F4 _does_ close OpenSpace without going through the timer.   I'd assume that Apple+Q would do the same on MacOS as well.

Other possible solutions:
 - reduce the shutdown countdown to 0 (https://github.com/OpenSpace/OpenSpace/blob/master/openspace.cfg#L228)
 -  instead of restarting OpenSpace, you can unload the asset instead and then reload it.  If you drag-n-drop a file, the `ScriptLog` has for example a `openspace.asset.add("C:/Development/OpenSpace/data/assets/scene/solarsystem/sssb/astraea.asset")` in it;  if you replace the `add` with `remove`, so `openspace.asset.remove("C:/Development/OpenSpace/data/assets/scene/solarsystem/sssb/astraea.asset")` it will remove the asset and you can drag it back in again to reload without a restart

**Comment by hedbergj** [comment]
Ha - of course it does.  I'm a doofus. ⌘-Q my new best friend. Thanks. Just need to re-write my motor neurons. 

I'll start trying to use the add/remove lines more - I seem to recall there was something funky about the remove in the past, but maybe it's better now.
