### ISSUE TITLE
Cannot render "Gaia Abundance Galah" or "Gaia Abundance Apogee" under Ubuntu 22.04

### ISSUE THREAD

**Issue by ChengtaoJi** [OpenSpace/OpenSpace#2429]
I cannot enable the "Gaia Abundance Galah" or "Gaia Abundance Apogee"  asset under the gaia profile, which prompt the error notes: 
terminate called after throwing an instance of 'std::__ios_failure'
  what():  basic_ios::clear: iostream error
Aborted (core dumped)

I compiled the Openspace under Ubuntu 22.04 with the following configuration: 
OpenGL version: 4.6
Using GLFW version 3.3.7
OpenGL version 4.6.0 core profile
Renderer: NVIDIA RTX A2000 8GB Laptop GPU/PCIe/SSE2
commit: master@8e383b218 uncommitted changes

**Comment by alexanderbock** [comment]
@GPayne are you getting the same issue?

**Comment by GPayne** [comment]
The crash happens because linux cares about case sensitivity in filenames, but windows does not.
You don't need to wait for this issue to be resolved; you can do a quick fix by going into your OpenSpace sync directory at:
**sync/http/stars_colormap/3/**
(depending on the version you're running this might be **/2/** instead) and rename the file to be uppercase letters where OpenSpace expects:
`mv rainbowgradient.cmap RainbowGradient.cmap`
and then it should run fine.

**Comment by GPayne** [comment]
Fixed in commit [25a6257](https://github.com/OpenSpace/OpenSpace/commit/25a62575ca83e3c23ccfe1241fa7f0e8ddcafa2d)
