### ISSUE TITLE
When creating a new configuration file with the Window Editor, the field-of-view values have the wrong defaults

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#2447]
A new configuration file gets created with hFov and vFov values of 0, which makes the configuration fail to load.

Potential duplicate of #2395

**Comment by GPayne** [comment]
I'm unable to replicate this. I assume this is with a planar projection configured from the window editor (because fisheye is the only other projection that uses a FOV). I tried all 5 projection types though, without a failure. When I save a file using planar projection I get FOV non-zero values that match either the default values (or new values if I modify them).

The file output uses the up/down/left/right values instead of the hfov/vfov values mentioned above. However this satisfies the sgct schema and it works for me; I get the correct horizontal & vertical FOV in the rendering, on both linux and windows.

**Comment by alexanderbock** [comment]
@alexanderbock Needs steps to reproduce

**Comment by alexanderbock** [comment]
Nevermind;  I'm unable to reproduce it as well
