### ISSUE TITLE
Some polishing for the Geolocation panel user interface

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#2585]
As discussed in the review meeting, it would be nice to rearrange some of the buttons and text fields in the GeoLocation panel to make it a bit more intuitive to use

**Comment by ylvaselling** [comment]
- Add function to remove a scene graph node
- Add NASA TREKS files to search from
- Have manual entry button for lat long
- Have a slider for altitude with airplane / ground
- Have km instead of m
- Default: use the size of the area from the api for how far up you should be

![Untitled](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/f74379e0-84a3-421d-a5ea-7c7180f49a41/Untitled.png)

**Comment by WeirdRubberDuck** [comment]
Closed in https://github.com/OpenSpace/OpenSpace-WebGuiFrontend/pull/153
