### ISSUE TITLE
config file from 0.18.2 not working for 0.19.0-RC1

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2633]
[BIGBANG.json.txt](https://github.com/OpenSpace/OpenSpace/files/11287847/BIGBANG.json.txt)

When I use this file in 19, the menus do not work. When I use the same file in 18, the menus do work.

**Comment by micahnyc** [comment]
[bigbang19.json.txt](https://github.com/OpenSpace/OpenSpace/files/11289178/bigbang19.json.txt)

Note: I ultimately wound up going with this one that works, but still curious about the behavioral difference with the old file between versions

**Comment by garrettsummerfi3ld** [comment]
I migrated three profiles generated with OpenSpace 0.18, works fine without issues. Is this CEF or is this the menu when pressing F1?

**Comment by GPayne** [comment]
The basic reason is that a change in the code since 0.18 requires that, for a multi-window config, the line:
`"tags": [ "GUI" ]`
must be present in the config file for a specific window, in order for the GUI to work in that window.
Your first file does not have this tag but the second does.

Also, PR#2719 (for issue#2531) will allow the first window to have rendering along with the GUI.
