### ISSUE TITLE
Crash due to unexpected date format in sssb_data_amor_asteroids.csv (Version 2)

### ISSUE THREAD

**Issue by Arohdin** [OpenSpace/OpenSpace#2649]
OpenSpace crashes when trying to load asteroids from `sssb_data_amor_asteroids.csv` .
This is due to unexpected date format/data in the file `sssb_data_amor_asteroids.csv` version 2.
This was added to BigBang here: [5ef6c75](5ef6c7502aacf30e9aead15ad907310c07666413)

According to function `epochFromYMDdSubstring()` in `kepler.cpp` the expected date format is `YYYYMMDD.ddddddd` where `YYYY` is the year, `MM` is the month (1-12), `DD` is the day (1-31) and `.ddddddd` is the fraction of a day.

In V1 of the .csv we see correct format for date, example:
`(1991 JR)", 19910512.0000000....` 
Date is: 1991 05 12

in V2 of the .csv we see:
`(1991 JR)",2448388.5....`
Date is: 2448 38 8X

So not only is the `MM` = 38, we're also missing one digit for `DD` .

**All dates in the new .CSV seems to be missing one digit and/or have incorrect `MM`**

**Comment by GPayne** [comment]
I am unable to reproduce this on linux or windows. I verified that I'm running with version 2 of these asteroid files, but I have no problems with rendering, no warnings or errors.
What you say about the date format is intersting, though. I'll look into that next. It is entirely possible that although they look fine visually, their positions are wrong due to this date format difference.

**Comment by Arohdin** [comment]
That is strange indeed.
For me it crashes due to it trying to access array for non-existing index.
`DaysOfMonths` contains 12 elements, but it tries to access between 0 - 37 .

![image](https://user-images.githubusercontent.com/9076357/234788245-f96181d5-b93a-46c5-b998-201c58ff13aa.png)

**Comment by GPayne** [comment]
I was able to reproduce the crash by building in **Debug** mode _and_ deleting the associated files from the cache folder (the cache files held the incorrectly-converted values from previous runs). Previously when in **RelWithDebInfo** mode, I didn't get the assertion, and I guess the code was simply getting the next byte in memory and using that to do an incorrect date conversion.

The root cause was me downloading the files with the epoch date in the wrong format (julian date). I'm going to re-download these, and overwrite the existing v2 files on our data servers with the new ones. The only users who would be adversely affected by this would be those who have already run the asteroids profile in v0.19. In such a case, they would not experience this crash because their downloaded version isn't Debug mode. Also, they would see a correct rendering of the orbital trail, but with the object in the wrong position along that trail. This could be remedied by deleting the sync and cache versions of these files.

**Comment by ElonOlsson** [comment]
I cannot get past this crash, no matter how much I'm removing cache and sync. Maybe I'm deleting the wrong files in Sync?

**Comment by Arohdin** [comment]
> I cannot get past this crash, no matter how much I'm removing cache and sync. Maybe I'm deleting the wrong files in Sync? 

I don't think the fix is implemented yet.
As a work around, build OpenSpace with RelWithDebInfo and build the cache using that.
For me it only crashes when building the cache with Debug build.

**Comment by GPayne** [comment]
PR#2728 will fix this. The reason the PR was required is that even after downloading updated files from JPL SBDB with the correct date format, they changed their format to add dashes in the date string (YYYY-MM-DD). The fix will handle both with and without the dashes, thus supporting our v1 _and_ v2 files from the sync servers.
