### ISSUE TITLE
Atmosphere - Enable Sun on Camera Position creates two suns

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2656]
If you use `openspace.setPropertyValueSingle("Scene.EarthAtmosphere.Renderable.SunFollowingCamera", true)` then you can wind up with two suns in the sky. 

We can probably set it so that it still renders the dot in the sun's real position. 

![image](https://user-images.githubusercontent.com/708535/234731236-4ba4dd20-152a-474f-a9a3-fa099b1700fa.png)

**Comment by hedbergj** [comment]
related: https://github.com/OpenSpace/OpenSpace/issues/1629

**Comment by alexanderbock** [comment]
Closing it as a wontfix.

The sun position is critically needed in all of the calculations for the atmosphere, so just faking the sun disk would not be enough as the glare would still be present above the camera location which looks equally bad (see second image).  If we fake the sun position everywhere, the resulting rendering would be the same as if the "Enable Sun on Camera Position" was not enabled in the first place.
It's probably possible to hack the atmosphere to get some halfway work done, but the added complexity is not worth it, specifically since the property very accurately describes what is happening.

![OpenSpace_000000](https://github.com/OpenSpace/OpenSpace/assets/4921724/1011a784-d193-4a97-9bfa-2c5b87c85a0d)
![OpenSpace_000001](https://github.com/OpenSpace/OpenSpace/assets/4921724/f9b7cfa2-b113-4dd9-93e6-13d67800754b)
