### ISSUE TITLE
Asteroids (RenderableOrbitalKepler) crashes when changing some PropertyValues

### ISSUE THREAD

**Issue by Arohdin** [OpenSpace/OpenSpace#2720]
When changing some property values for type RenderableOrbitalKepler, such as `SegmentQuality` or `RenderSize`, via either script or GUI the program crashes.
Checking the script that's being executed it seems correct:
`openspace.setPropertyValueSingle("Scene.sssb_amor_asteroid.Renderable.SegmentQuality", 5.000000)`
`openspace.setPropertyValueSingle("Scene.sssb_amor_asteroid.Renderable.RenderSize", 11000.000000)`

The program seems to crash when interpreting the Lua script in `scriptengine.cpp` line 213: `ghoul::lua::runScript(_state, script);`

![image](https://github.com/OpenSpace/OpenSpace/assets/9076357/23859def-1b6d-4ab2-8a98-0b876d62aecf)

However, if you run the same command, but using INT instead of FLOAT in the argument, it works:
`openspace.setPropertyValueSingle("Scene.sssb_amor_asteroid.Renderable.SegmentQuality", 5)`
`openspace.setPropertyValueSingle("Scene.sssb_amor_asteroid.Renderable.RenderSize", 11000)`

**Comment by alexanderbock** [comment]
The issue was the the UIntProperty did not check whether the number coming from the Lua stack was a lua_Number.  So setting a UIntProperty to `123.0` was not allowed and caused a crash even though it is an integer.  setting it to `123` worked but our UI generates the former.  We had a check for the IntProperty and didn't copy it over to the UIntProperty
