### ISSUE TITLE
Error loading .geojson file

### ISSUE THREAD

**Issue by Doming7** [OpenSpace/OpenSpace#2811]
When loading a geojson file I downloaded from the web, I got an error loading due to the credits entry in the file. When I deleted the credits entry it worked.

[ASE_2021.06.10.txt](https://github.com/OpenSpace/OpenSpace/files/11971243/ASE_2021.06.10.txt)

Error creating GeoJson layer with identifier 'GeoJson_Files'. Problem reading GeoJson file 'E:\OpenSpace\OpenSPace_KML_Files\Master\GeoJson_Asset\../GeoJson_Files/ASE_2023.10.14.geojson'. Error: 'ParseException: Error parsing JSON: '[json.exception.type_error.304] cannot use at() with null''

**Comment by WeirdRubberDuck** [comment]
Ok, so the problem here is that the library we use for parsing the GeoJson files does not support `null` geometry (which IMO it should, as null objects are mentioned in the GeoJson specification)

I expect that more issues related to this will emerge down the line (the library seems to only support "nice" and well-defined objects), but made a quick fix in our fork of the library to support this use case (c973cee5a12b11f6d464db14120ce602f39f2a4a). However, the feature will not show up in the interface, as of now.

One thing that caught my eye is how not-useful that error message is to a user. This should be improved... One way of doing so is covered by this issue: https://github.com/OpenSpace/OpenSpace/issues/2835
