### ISSUE TITLE
Fix SPICE offset issue

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#3]
<a href="https://github.com/alexanderbock"><img src="https://avatars.githubusercontent.com/u/4921724?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [alexanderbock](https://github.com/alexanderbock)**
_Thursday May 05, 2016 at 20:50 GMT_
_Originally opened as https://github.com/OpenSpace/OpenSpace-Development/issues/1_

---

The image projection onto Pluto from New Horizons using SPICE has a slight offset for different image campaigns.

**Comment by EricMyers47** [comment]
Can I get the exact value of the offset?

**Comment by EricMyers47** [comment]
I have an idea what might be causing this, based on hearing from Carter that the timing offset is around 4 seconds.  

It's possible that this could be due to using different times from SPICE, eg. spacecraft time for the timing of images (that makes sense to me) but Ephemeris Time (TDB) for navigation information (which also makes sense to me, but I don't know how it's done).   The thing is, for a long mission to the outer solar system these two will not be the same, due to relativity.    In fact, relativity has to be accounted for in New Horizons, so it will be interesting to see it.

The idea is the same as how relativity affects GPS satellites.   The satellites in orbit around the Earth are traveling fast, and they are also at a different gravitational potential, and both of those lead to a very small time dilation.   They actually work opposite each other, so there is one orbital radius where they cancel, but the GPS satellites are not at that altitude.   The net effect is that the atomic clocks on the GPS satellites tick at a slightly different rate as clocks on the surface of the Earth.  This is cumulative;  after one day the time difference would be enough to throw the navigation position reported by GPS off by up to 10km.   So they make a "factory correction" to the GPS signal, reporting not the time on the satellite, but the time that it would be if relativity didn't exist.   Doing the correction on the satellite makes it much easier to use the signal for navigation and timing (it's then just triangulation in space and time, or least-squares fitting if you can get more than 4 satellites).   The fact that the orbits are circular makes this correction easier.

Okay, that's GPS, but the same thing happens to Earth going around the Sun.    The clocks on Earth tick at a slightly different rate, due to our position in the gravitational well of the Sun and our speed, compared to clocks elsewhere, and specifically clocks far away from the Sun, what I'll call deep-space time.    The effect is cumulative and adds up to about 0.5 seconds per year.   There should be a leap second every 2 years, except that since everybody who uses clocks lives on the surface of the Earth, we've had no need for a correction.    Now that we can send something to Pluto, where there is no relativistic effect, the difference in times will be important.     And the numbers seem to work, because after 8 or 9 years away from the Earth, the clocks on New Horizons would differ from clocks on Earth by about 4 seconds.

I don't know if this is what is causing this particular issue, but it gives us something to check.   My guess is that one has simply to convert spacecraft time (SCLK) to Ephemeris time (TDB) to get events to match up, and the SPICE Toolkit has an API to do this.   I'm not sure yet how this is done;  because the effect is cumulative and depends on the path taken by the spacecraft, the time difference must be recorded in one of kernels.    But the API should take care of that.

I'm still learning more about SPICE.   I found these slides helpful: https://naif.jpl.nasa.gov/pub/naif/toolkit_docs/Tutorials/pdf/individual_docs/15_time.pdf

Even if this does not explain this particular issue, the time difference should be there and is interesting as a demonstration of relativity, so I want to learn more about it.

**Comment by emiax** [comment]
woah, cool! definitely sounds like this is worth looking into. It has not
occured to me that the relativistic effects could be that big just inside
our solar system. + great explaination, Eric!

**Comment by alexanderbock** [comment]
Potential sources ruled out:
  1. New set of kernels lead to the same problem
  2. Tried old size (1173) of Pluto vs new size (1185)
  3. It's not a fixed time offset as the projected images have a relative offset in that case

Observations:
  1. Offset is a non-linear deformation and dependent on the location of the image on the planet:
  2. Offset between projected images seems much smaller compared to projected vs background (maybe a problem with the map projection that is used?)

![sgct_openspace_000001](https://cloud.githubusercontent.com/assets/4921724/23591867/83559f46-01c5-11e7-9dda-f6156cd3dd3d.png)
![sgct_openspace_000002](https://cloud.githubusercontent.com/assets/4921724/23591868/835741fc-01c5-11e7-9588-46135ef0a28a.png)

**Comment by alexanderbock** [comment]
It was not a bug in the image projection, but caused by using the basemap with a set of SPICE kernels that were not corrected.  After a debugging session with Ross Beyer and Paul Schenk, it fits perfectly now.

**Comment by kbladin** [comment]
Dayum! Great work!
