### ISSUE TITLE
Generate markdown file(s) from the generated documentation file

### ISSUE THREAD

**Issue by ylvaselling** [OpenSpace/OpenSpace#3032]
The markdown file(s) would be useful to put on the wiki (docs) page. 

@alexanderbock can maybe flesh out this issue

**Comment by alexanderbock** [comment]
Using the issue #2355 we can have a script that takes the JSON file, generate Markdown files that we can then push into the docs.openspaceproject.com repository.
The idea being that we'd do this every time when we release a new version so that "normal" users that don't build OpenSpace themselves can find the fixed aspects of the documentation that _don't_ change depending on the profile also on the docs page. Inspiration for this was from the Godot documentation (https://docs.godotengine.org/en/stable/classes/index.html).

**Comment by alexanderbock** [comment]
Duplicate of #2996

**Comment by ylvaselling** [comment]
Done with the new docs page
