### ISSUE TITLE
Background image can reduce contrast on text fields

### ISSUE THREAD

**Issue by meganvilla** [OpenSpace/OpenSpace#3094]
The overlay may have a different background image every time when opened. The text of the dropdown labels can be difficult to read when their text is positioned over lighter colors in the background image

Here are some examples where the white label text (#FFF) is difficult to read, and our suggested remediation path:
- The entire "Choose Profile" label can be positioned over a satellite image of Earth with light colors, e.g. #BBB8A9 resulting in a color contrast ratio of 2:1.
- The last letters of "Window Options" may appear over a beige (#7B7C74) shade of the Jupiter planet and the resulting color contrast ratio is 4.2:1.
- When the background image shows a rocky surface, some letters in "Choose Profile" appear on a light gray (#9F9F9F) background and have a 2.6:1 color contrast.

**Suggested Solution:** Add a background color or drop shadow to the text content and ensure that normal-sized text meets the minimum color contrast requirement of 4.5:1. 

Severity level 2 from PAC

**Comment by engbergandreas** [comment]
Ideally, we would add a `box-shadow` or blur to the background color to reduce the hard edges it would otherwise create. It does not seem that qt supports either on the `QLabel` so we opt instead to create a template for the background images to do the blurring or add a box (or similar) where the text goes
