### ISSUE TITLE
openspace.time.deltaTime() returns 0 when paused

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#3158]
I would expect it to still return a value for the delta time even when paused. We should probably add a separate function for openspace.time.isPaused()

**Comment by alexanderbock** [comment]
I'd vote to close this as it's going to increase the hacking-ness factor quite a lot.  In order to support interpolating the delta time to a pause we _actually_ have to change the delta time and can't just fake it.  Storing the previous delta time while doing that interpolation will fail if someone spams the space bar and will leave the `deltaTime` function unreliable.
