### ISSUE TITLE
pluto dwarf planet texture renders only one side of pluto

### ISSUE THREAD

**Issue by hn-88** [OpenSpace/OpenSpace#3167]
I was trying to make some flybys of some solar system objects, and found the following issue with Pluto - only one side is shown with relatively high resolution, one side is low res. Is this by design? because we only have data for one side? Or is this a bug? Is this related to  https://github.com/OpenSpace/OpenSpace/issues/1895 ? Or some problem at my end? I do see an error message as below, but the program does work with hardware acceleration, 100+ fps - 

```
[0408/111221.776:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is disabled, ANGLE is
```

What I used: OpenSpace v 19.2 on Windows, Default window configuration, default profile, fly to Pluto, use rotation to go around it. Screenshot below.
![image](https://github.com/OpenSpace/OpenSpace/assets/6321069/603b9c20-15ce-444b-a775-cb93b6ee27c7)

**Comment by hn-88** [comment]
Testing on another machine, I see some warning messages which might be relevant - could not open dataset:

```
(W) GlobeBrowsingModule  Could not open dataset: https://planetarymaps.usgs.gov/cgi-bin/mapserv?map=/maps/mercury/mercury_simp_cyl.map&service=WMS&request=GetCapabilities
(W) GlobeBrowsingModule  Could not open dataset: https://gibs.earthdata.nasa.gov/twms/epsg4326/best/twms.cgi?request=GetTileService
(W) GlobeBrowsingModule  Could not open dataset: https://planetarymaps.usgs.gov/cgi-bin/mapserv?map=/maps/pluto/pluto_simp_cyl.map&service=WMS&request=GetCapabilities
(W) GlobeBrowsingModule  Could not open dataset: https://planetarymaps.usgs.gov/cgi-bin/mapserv?map=/maps/pluto/charon_simp_cyl.map&service=WMS&request=GetCapabilities
(I) SpeckLoader          Cached file "D:\\OpenSpace-0.19.2\\OpenSpace-0.19.2\\cache\\SDSSgals.cmap\\2259649777\\SDSSgals.cmap" used for file "D:\\OpenSpace-0.19.2\\OpenSpace-0.19.2\\sync\\http\\digitaluniverse_sloandss_speck\\2\\SDSSgals.cmap"
(D) SceneGraphNode       Finished initializing: SloanDigitalSkySurvey
[0408/140732.724:INFO:child_thread_impl.cc(903)] ChildThreadImpl::EnsureConnected()
(E) HttpRequest          Failed download https://www.celestrak.com/NORAD/elements/gp.php?GROUP=last-30-days&FORMAT=kvn with error Couldn't connect to server
```

Some way to force retry?

**Comment by WeirdRubberDuck** [comment]
As you were onto in your first comment, this is a result from the dataset itself (the warnings in in your second comment is unrelated).  
The data is from the New Horizons mission and the LORRI telescope aboard the spacecraft, and it only captured images of Pluto's surface during one fly by, so me only have high-res data from that viewing direction. 
https://en.wikipedia.org/wiki/Long_Range_Reconnaissance_Imager 

Here's a page with the dataset, showing the amount of data coverage
https://www.jpl.nasa.gov/images/pia19858-global-map-of-pluto

Pluto is completely black on one side because the dataset we are showing does not have data covering that side at all (to my knowledge, there does not exist one). And in the transition between the parts with no data and the high-res part, there is an area where the quality os the image is not as high due to the curvature of the dwarf planet

**Comment by alexanderbock** [comment]
Correct, for the black part of that map we only have the Hubble images, whose even lower resolution would very jarring, so we decided to not include it

https://api.time.com/wp-content/uploads/2015/04/pluto-hubble.jpg?quality=75&w=1690
