### ISSUE TITLE
Add the ability to pass parameters to asset.require and asset.request

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#442]
It would be useful to be able to pass parameters into a `require` or `request` that are accessible (or `nil` if they not set) in the asset that is included.

Potential use case:  Conditional inclusion depending on user changable parameters without requiring the user to dig deep into asset files

**Comment by emiax** [comment]
Yeah, that would be useful. I considered it as part of the asset system, but ran into the issue of what should happen if several assets require/request the same one with different parameters.

I.e.
```
A:
asset.require(C, {includeD = true})
B:
asset.require(C, {includeD = false})
C:
if (includeD) asset.require(D) end
```
Should C be included twice? Should the second requrement throw an error? Etc.

For exposing parameterizable behaviour from C, I think it makes sense to export functions (much like assethelper is already doing). However, this wont work for conditional inclusion for require/request-statements since they are performed when loading the asset.

It should be possible to add support for calls to `asset.request` (but not require) after initialization. This may already work, but I am not sure if it behaves correctly at this moment. 

Solution would be:

```
A:
asset.require(C)
C.includeD();

B:
asset.require(C)

C:
function addD()
    asset.request(D) // This may already work, but is untested.
end 
function removeD() 
    asset.unrequest(D) // Not implemented yet, but should be possible.
end
export("addD", addD)
export("removeD", removeD)
```

**Comment by alexanderbock** [comment]
Yeah, let's leave it out for now;   right now, the workaround is to use global variables in the Lua context
