### ISSUE TITLE
Inconsistency with wiki / No option to choose what to sync on MacOS 

### ISSUE THREAD

**Issue by sophiavanvalkenburg** [OpenSpace/OpenSpace#476]
Hi, I built the Debug version on MacOS (High Sierra 10.13.1) with Xcode 9.2. I followed the wiki instructions to run the app. I got to the step `open -n OpenSpace.app <args>`. The application opens but goes right to the Loading and Synchronizing Assets stage without giving me the option to select what to sync. It got stuck loading 'Mars Spice Kernels' which I left for about 36 hours and never finished. So I have the following questions:

1. Is it normal for the assets to take that long to load? (I have a MacBook from 2013 so it could be slow/underpowered)
2. I would like to see if I can run the application without synching everything, but I don't see an option to do so. I tried running Sync.app by itself and got the error `LSOpenURLsWithRole() failed with error -10810 for the file ~/workspace/OpenSpace/bin/Debug/Sync.app`

![screen shot 2018-02-03 at 11 30 23 am](https://user-images.githubusercontent.com/9573929/35769276-8109daea-08d6-11e8-82c7-e800a08201c9.png)

**Comment by hedbergj** [comment]
I had better luck just getting all the files from the google drive links on this page:

[http://openspaceproject.com/?page_id=977](http://openspaceproject.com/?page_id=977)

Then put them in place manually (all in the sync folder). You can also select to not load things by playing with the `openspace.cfg` file in the main directory.

**Comment by alexanderbock** [comment]
@hedbergj   Thank you for your suggestion and I can second that;

OpenSpace only synchronizes the data that is needed for the scene that is specified in the `Asset` key of `openspace.cfg`  (or if you overwrite it using commandline arguments).  If you leave the asset unset, it should load a completely empty scene.  To modify what you want to load, you can edit the `data/assets/default.scene` and remove some of the `asset.require` or `asset.request` calls that are made in that Lua file.

@sophiavanvalkenburg   That was a bug that was missed in testing, but we have since fixed it as of commit 92b88fe5b ;  now the synchronization correctly shows the percentage and finishes as well.

The Sync application was using the same code, so it didn't finish before either;  I  have not seen the `LSOpenURLsWithRole` method before or seeing it fail.  Can you try opening the application without the app bundle, by `./OpenSpace.app/Contents/MacOS/OpenSpace`  and see if it is still persisting?

**Comment by sophiavanvalkenburg** [comment]
@hedbergj @alexanderbock great, I think the fix for https://github.com/OpenSpace/OpenSpace/commit/92b88fe5b655866f494bb8befb585dc133f7404b worked. I was able to load everything and run the application! Thank you.
