### ISSUE TITLE
Jenkins compile error related to constexpr

### ISSUE THREAD

**Issue by emiax** [OpenSpace/OpenSpace#501]
Jenkins reports an error on linux:
The call to
```
void internal_assert(std::string expression, std::string message, std::string file,
    std::string function, int line);
```

from the ```ghoul_assert``` macro used in timeconversion.h:161 is a call to a non-constexpr function from a constexpr function.

Google tells me this behaviour is different in C++11/14. Do we need to update our version of gcc on the jenkins machine, or should the code be changed?

**Comment by alexanderbock** [comment]
The ghoul_assert was a true bug, since we can't make assert constexpr (and it doesn't make much sense either way).  I fixed that.

However, there is a another compile error about `std::array::begin` and `std::array::end` not being constexpr, which they have been since C++17 .  So yeah, I'll go and update the GCC there

http://en.cppreference.com/w/cpp/container/array/begin

**Comment by alexanderbock** [comment]
One part fixed for Linux (updated GCC and made C++17 required in CMake)

One part remaining (updating Clang version on MacOS)

**Comment by alexanderbock** [comment]
Gene updated Clang on MacOS which fixed the issue
