### ISSUE TITLE
Dome casting Camera bounce

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#523]
While dome casting, the camera on the client side bounces

  - Problem with the camera interpolation?
  - Depends on camera location?
  - Depends on delta time?

**Comment by emiax** [comment]
Can you describe a little more when the problem occurs?
There is one known issue, when the camera is orbiting an object fast: Since the interpolation between camera positions is linear, and camera position is sent n times per orbit, the camera will essentially move in a polygon with n sides. 

However, this should not be dependent on delta time, so I wonder if there is some other issue that you see.
