### ISSUE TITLE
RenderableTrailTrajectory does not go through center of spacecraft when full trail is enabled

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#625]
For example when lookign at Juno and enabling the full trail for the space craft + orbit lines.  If done, they don't match up with the accurate location

Possible solution:  Having the floating position in there as well?

**Comment by Roxeena** [comment]
To clarify what the problem is: When looking up close at Juno and enabling the full trail, it does not go through the center of the spacecraft. This is because the full trail is calculated with lower precision than the normally shorter trail and is therefore less accurate.

How to reproduce: Choose the Juno profile, zoom in to see Juno, enable the full trail on the Juno Trail, let some simulation time pass to see it more clearly.

![example](https://user-images.githubusercontent.com/16215103/106161387-343fae80-6187-11eb-8528-3bef7f854a94.gif)

**Comment by Arohdin** [comment]
Being worked on in branch [Issue/625](https://github.com/OpenSpace/OpenSpace/tree/issue/625)

**Comment by Arohdin** [comment]
Created PR #2766
