### ISSUE TITLE
Gaia module doesn't load files properly on mac

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#843]
There is an issue with the trailling / and the sync folders. Even though the .asset files says :

File = starsFolder .. "/" 

when looking at the error in the logs, it is trying to load the file SYNCDIR/1dataset/index.bin rather then SYNCDIR/1/dataset/index.bin

**Comment by micahnyc** [comment]
fixd with ghoul commit: https://github.com/OpenSpace/Ghoul/commit/629a0c09be20431077c365f6fa3ae4c21d7c1f85

will close once master is updated

**Comment by micahnyc** [comment]
Not working again in 0.16.0, need more info

**Comment by alexanderbock** [comment]
See if it is still an issue currently or where in the rendering the change was made that broke it

**Comment by alexanderbock** [comment]
Multiple issues for this:
1. Synchronization on Mac fails as the RV datasets tries to sync too many files at once, causing some of them to fail.  A workaround is to start the scene again which successfully downloads more files, but fails again.  Rinse and repeat for a few iterations (4 starts on my laptop) and all files are successfully synchronized
2. The allowed rendering methods were switched between windows and mac (fixed in d08e2565ac47280070f65be53c8fe182a5f268b1)
3. The VBO methods only render for a single frame on my laptop.  However, the memory on that machine is heavily limited and I don't know if it is related to the GPU running out of memory.

My suggestion would be to officially consider the Gaia profile broken on Mac

**Comment by alexanderbock** [comment]
To be determined whether we still want this or not

**Comment by micahnyc** [comment]
Add message and warning that module not supported on mac.
