### ISSUE TITLE
Issue starting 0.14.0 on MacOS

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#884]
Dyld Error Message:   Library not loaded: @rpath/libfreeimage.3.17.0.dylib   Referenced from: /Applications/OpenSpace-0.14.0/*/OpenSpace.app/Contents/MacOS/OpenSpace   Reason: image not found

**Comment by alexanderbock** [comment]
The MacOS version links against version 3.18 of libfreeimage (libfreeimage.3.18.0.dylib), which is not a hard requirement;  it would be better if that version can be linked against the base version (libfreeimage.3.dylib or even libfreeimage.dylib), making it possible to start on machines with slightly older versions.

**Comment by micahnyc** [comment]
Fixed with 0.14.1 however the the solution was to ship the libfreeimage with the binary as we do with GDAL etc. I still need to investigate if libfreeimage is distributed with osx or if we need to continue including it. Closing for now and will do the investigation when doing a larger effort around MacOS deployment.
