### ISSUE TITLE
Issue with transparency with RenderableTrails in the Apollo scene

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#885]
After the TLI event, the Earth-centric launch orbit are not correctly rendered relative to the atmosphere

**Comment by alexanderbock** [comment]
Additionally, the global trail is not correctly culled against Earth

**Comment by emiax** [comment]
Currently, all renderables decide what render bin they should belong to based on their opacity. However, if they are using additive blending (which trails should, since the fade-over-time aspect makes them translucent generally) they should always render in the trasparent bin.

Here is the change that introduced a general renderbin detection for renderables: https://github.com/OpenSpace/OpenSpace/pull/618/files#diff-164881db16899efa14f4b2d3abc68736R104

This should also be a problem for other renderables that have a blend mode option, like RenderableSphere.

I suggest we remove the automatic selection of render bin, since the bin may depend on other things than the `_opacity` property. If trails render to the transparent bin, and do so with additive blending, the problem will disappear.

**Comment by emiax** [comment]
Will create a PR for this change

**Comment by emiax** [comment]
I thought this would be straight forward, but simply making trails use additive blending makes one problem remain: The atmosphere will pick up the position and normals written by the trail, and get affected by it, so even if the trail is completely transparent, it will affect the look of the atmosphere.
An alternative would be to have transparent geometry NOT write to the position + normal buffers. The result of this is that the atmosphere will always be rendered "on top" of of the trail. There is no longer any trace of the transparent trail, but there is a drastic shift in appearance of the trail depending on if the atmosphere is rendered on the same pixel or not. The atmosphere is rendered on top, changing the color of the trail as if would be located on the planetary surface.

As I currently see it, the proper way to solve this is to draw the trails (potentially along with other transparent geometry) after the atmosphere. This is not trivial at this point, since the atmosphere is so involved in the HDR rendering. @jccosta, I think it would be good to have a meeting soon and talk more about your HDR changes, and catch up in general.

**Comment by jccosta** [comment]
@emiax I think we should talk too. There is another inherent problem with the trails and transparency.  The Sun's glare is also a transparent billboard and it must be rendered after all trails, otherwise you can get the wrong blending sorting. What is the requirement for having transparent trails? The end "tail" being eroding?

**Comment by emiax** [comment]
Here are some suggestions:

![rendering-pipeline](https://user-images.githubusercontent.com/1081118/59104580-39a51100-8932-11e9-8654-be4349024b80.png)

Regarding the sun glare, I don't see that as a separate problem: If it is rendered with additive blending, then sorting is not necessary. I think trails, sun glare, and basically all transparent geometry should both render with additive blending to avoid these problems.

The issue you bring up with depth sorting remains whenever we need something to be translucent and still occlude geometry behind it (non-additive blending). I don't think that is necessary for any of our current content, but if we want it, we need depth sorting / order-independent transparence (like A-buffer).
