### ISSUE TITLE
Performance issue with WebGUI scrolling

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#976]
At least on the Norrköping dome, the mouse wheel scrolling when going through the WebUI menu reduces the performance quite a lot as it seems to be doing some blocking work.

**Comment by emiax** [comment]
I did some investigations along these lines:
- Opened a static html page (no JS) inside CEF in OpenSpace, instead of our WebGUI.
- Measured time when scrolling up and down:
  - Total extra time per frame: approx 40ms (SUPER BAD)
  - Copying pixel data from CEF to CPU buffer: 2.5ms
  - Uploading pixel data from CPU to GPU: not much
  - `doMessageLoopWork`: 30ms <- This is the main time consumer

From what I've gathered so far is that the browser is simply taking a long time to re-render the page.

**Comment by liuloppan** [comment]
This issue has been improved by @stefanseibert  #1017 Improvements in Performance due to adopted usage of CEF Message Loop
